apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: {{ required "namespace must be set" .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: chat-ui
  ports:
    - port: {{ .Values.chatUI.port }}
      targetPort: {{ .Values.chatUI.port }}
      nodePort: {{ required "chatUI.nodePort must be set" .Values.chatUI.nodePort }}
