apiVersion: v1
kind: Service
metadata:
  name: chat-ui
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: chat-ui
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: {{ .Values.chatUI.nodePort }}
